using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Accenture.DirectoryStatistics
{
    /// <summary>
    ///     A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode]
    [CompilerGenerated]
    public class Resources
    {
        private static ResourceManager resourceMan;

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///     Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new ResourceManager("Pat.QA.WebUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///     Overrides the current thread's CurrentUICulture property for all
        ///     resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture { get; set; }

        /// <summary>
        ///     Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ChromeDriver
        {
            get
            {
                var obj = ResourceManager.GetObject("ChromeDriver", Culture);
                return (byte[]) obj;
            }
        }

        /// <summary>
        ///     Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IEDriverServer32
        {
            get
            {
                var obj = ResourceManager.GetObject("IEDriverServer32", Culture);
                return (byte[]) obj;
            }
        }

        /// <summary>
        ///     Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IEDriverServer64
        {
            get
            {
                var obj = ResourceManager.GetObject("IEDriverServer64", Culture);
                return (byte[]) obj;
            }
        }

        /// <summary>
        ///     Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PhantomJS
        {
            get
            {
                var obj = ResourceManager.GetObject("PhantomJS", Culture);
                return (byte[]) obj;
            }
        }
    }
}